# Generated by Django 5.2.2 on 2025-06-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0003_equipement_localisation_equipement_type'),
        ('usager', '0003_alter_usager_est_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('assistance', models.BooleanField(default=False)),
                ('est_formation', models.BooleanField(default=False)),
                ('courriels_formes', models.TextField(blank=True, help_text='Uniquement pour les réservations de type formation. Séparer les courriels par des virgules.')),
                ('demande_exception', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('passee', 'Passée'), ('annulee', 'Annulée'), ('en_attente', 'En attente (exception)')], default='a_venir', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.equipement')),
                ('usager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usager.usager')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date', 'heure_debut'],
            },
        ),
    ]
