# Generated by Django 5.2.2 on 2025-06-06 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_debut', 'heure_debut'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='date_debut',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_fin',
            field=models.DateField(default=datetime.date(2025, 6, 6)),
            preserve_default=False,
        ),
    ]
