# Generated by Django 5.2.2 on 2025-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0002_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duree_assistance_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Durée de l'assistance technique en minutes (rempli par un admin)", null=True),
        ),
    ]
