# Generated by Django 4.2.24 on 2025-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0004_alter_reservation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('a_venir', 'À venir'), ('passee', 'Passée'), ('annulee', 'Annulée'), ('en_attente', 'En attente (exception)')], default='a_venir', max_length=20),
        ),
    ]
