# Generated by Django 4.2.25 on 2025-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0006_reservation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='est_enseignement',
            field=models.BooleanField(default=False, help_text='Réservation pour enseignement (cours de labo)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='est_maintenance',
            field=models.BooleanField(default=False, help_text="Réservation pour maintenance/hors service (bloque l'équipement)"),
        ),
    ]
