# Generated by Django 5.2.2 on 2025-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
