# Generated by Django 5.2.2 on 2025-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0002_equipement_actif_equipement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='localisation',
            field=models.CharField(default='inconnu', help_text="Lieu ou salle où se trouve l'équipement", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipement',
            name='type',
            field=models.CharField(choices=[('microscope', 'Microscope'), ('cytomètre', 'Cytomètre'), ('analyse', 'Poste d’analyse'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
