# Generated by Django 5.2.2 on 2025-06-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0003_equipement_localisation_equipement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine concerné (0 = Lundi, 6 = Dimanche).')),
                ('heure_debut', models.TimeField(help_text='Heure de début du créneau (ex: 08:00).')),
                ('heure_fin', models.TimeField(help_text='Heure de fin du créneau (ex: 12:00).')),
                ('equipement', models.ForeignKey(help_text='Équipement concerné par ce créneau.', on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='equipements.equipement')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['equipement', 'jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='PlageLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (0 = Lundi, etc.).')),
                ('heure_debut', models.TimeField(help_text='Début de la plage horaire contrôlée.')),
                ('heure_fin', models.TimeField(help_text='Fin de la plage horaire contrôlée.')),
                ('duree_max_minutes', models.PositiveIntegerField(help_text='Durée maximale cumulée autorisée par usager dans cette plage (en minutes).')),
                ('equipement', models.ForeignKey(help_text='Équipement concerné par cette plage de limitation.', on_delete=django.db.models.deletion.CASCADE, related_name='plages_limite', to='equipements.equipement')),
            ],
            options={
                'verbose_name': 'Plage limitée',
                'verbose_name_plural': 'Plages limitées',
                'ordering': ['equipement', 'jour', 'heure_debut'],
            },
        ),
    ]
