# Generated by Django 5.2.2 on 2025-06-11 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0004_creneau_plagelimite'),
        ('usager', '0004_remove_usager_equipements_accessibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_horaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usager.affiliation')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='equipements.equipement')),
            ],
            options={
                'unique_together': {('equipement', 'affiliation')},
            },
        ),
    ]
