# Generated by Django 5.2.2 on 2025-06-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0005_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='formation_theorique',
            field=models.BooleanField(default=False, help_text='Cochez si les formations sur cet équipement doivent être considérées comme théoriques.'),
        ),
    ]
