# Generated by Django 4.2.24 on 2025-09-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0006_invitation'),
        ('equipements', '0006_equipement_formation_theorique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarif',
            options={'verbose_name': 'Tarif', 'verbose_name_plural': 'Tarifs'},
        ),
        migrations.AddField(
            model_name='tarif',
            name='tarif_assistance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarif horaire d’assistance en CAD/h (optionnel, ex: 40.00).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='affiliation',
            field=models.ForeignKey(help_text='Affiliation (université, organisme) pour laquelle ce tarif est défini.', on_delete=django.db.models.deletion.CASCADE, to='usager.affiliation'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='equipement',
            field=models.ForeignKey(help_text='Équipement auquel s’appliquent ces tarifs.', on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='equipements.equipement'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='tarif_horaire',
            field=models.DecimalField(decimal_places=2, help_text='Tarif horaire standard en CAD/h (ex: 25.00).', max_digits=6),
        ),
    ]
