# Generated by Django 4.2.24 on 2025-09-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0006_invitation'),
        ('equipements', '0007_alter_tarif_options_tarif_tarif_assistance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarif',
            name='tarif_assistance',
        ),
        migrations.AlterField(
            model_name='tarif',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usager.affiliation'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='equipements.equipement'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='tarif_horaire',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
