# Generated by Django 4.2.24 on 2025-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0008_remove_tarif_tarif_assistance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='duree_max_heures',
            field=models.PositiveIntegerField(default=72, help_text="Durée max d'une réservation en heures (sauf demande exceptionnelle)."),
        ),
    ]
