# Generated by Django 4.2.24 on 2025-10-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0007_invitation_date_validation_invitation_reservation_and_more'),
        ('equipements', '0009_equipement_duree_max_heures'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_formation', models.DecimalField(decimal_places=2, help_text='Prix fixe (CAD) pour la formation', max_digits=8)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usager.affiliation')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_formation', to='equipements.equipement')),
            ],
            options={
                'verbose_name': 'Tarif formation',
                'verbose_name_plural': 'Tarifs formation',
                'unique_together': {('equipement', 'affiliation')},
            },
        ),
    ]
