# Generated by Django 4.2.24 on 2025-10-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0010_tarifformation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarif',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tarifformation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='formation_theorique',
        ),
        migrations.AddConstraint(
            model_name='tarif',
            constraint=models.UniqueConstraint(fields=('equipement', 'affiliation'), name='unique_tarif'),
        ),
        migrations.AddConstraint(
            model_name='tarifformation',
            constraint=models.UniqueConstraint(fields=('equipement', 'affiliation'), name='unique_tarif_formation'),
        ),
    ]
