# Generated by Django 4.2.25 on 2026-05-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_duration_hours', models.PositiveIntegerField(default=72, help_text="Durée max d'une réservation en heures (sauf demande exceptionnelle).")),
                ('type', models.CharField(choices=[('microscope', 'Microscope'), ('cytomètre', 'Cytomètre'), ('analyse', 'Poste d’analyse'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('location', models.CharField(help_text="Lieu ou salle où se trouve l'équipement", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (0 = Lundi, etc.).')),
                ('start_time', models.TimeField(help_text='Début de la plage horaire contrôlée.')),
                ('end_time', models.TimeField(help_text='Fin de la plage horaire contrôlée.')),
                ('max_duration_minutes', models.PositiveIntegerField(help_text='Durée maximale cumulée autorisée par user_profile dans cette plage (en minutes).')),
                ('equipment', models.ForeignKey(help_text='Équipement concerné par cette plage de limitation.', on_delete=django.db.models.deletion.CASCADE, related_name='plages_limite', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Plage limitée',
                'verbose_name_plural': 'Plages limitées',
                'ordering': ['equipment', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_fee', models.DecimalField(decimal_places=2, help_text='Prix fixe (CAD) pour la formation', max_digits=8)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.affiliation')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_rates', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Rate formation',
                'verbose_name_plural': 'Rates formation',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine concerné (0 = Lundi, 6 = Dimanche).')),
                ('start_time', models.TimeField(help_text='Heure de début du créneau (ex: 08:00).')),
                ('end_time', models.TimeField(help_text='Heure de fin du créneau (ex: 12:00).')),
                ('equipment', models.ForeignKey(help_text='Équipement concerné par ce créneau.', on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['equipment', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.affiliation')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
        migrations.AddConstraint(
            model_name='trainingrate',
            constraint=models.UniqueConstraint(fields=('equipment', 'affiliation'), name='unique_training_fee'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('equipment', 'affiliation'), name='unique_tarif'),
        ),
    ]
