# Generated by Django 4.2.25 on 2026-05-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duree_max_heures', models.PositiveIntegerField(default=72, help_text="Durée max d'une réservation en heures (sauf demande exceptionnelle).")),
                ('type', models.CharField(choices=[('microscope', 'Microscope'), ('cytomètre', 'Cytomètre'), ('analyse', 'Poste d’analyse'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('localisation', models.CharField(help_text="Lieu ou salle où se trouve l'équipement", max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarifFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_formation', models.DecimalField(decimal_places=2, help_text='Prix fixe (CAD) pour la formation', max_digits=8)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.affiliation')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_formation', to='equipment.equipement')),
            ],
            options={
                'verbose_name': 'Tarif formation',
                'verbose_name_plural': 'Tarifs formation',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_horaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.affiliation')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='equipment.equipement')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
            },
        ),
        migrations.CreateModel(
            name='PlageLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (0 = Lundi, etc.).')),
                ('heure_debut', models.TimeField(help_text='Début de la plage horaire contrôlée.')),
                ('heure_fin', models.TimeField(help_text='Fin de la plage horaire contrôlée.')),
                ('duree_max_minutes', models.PositiveIntegerField(help_text='Durée maximale cumulée autorisée par usager dans cette plage (en minutes).')),
                ('equipement', models.ForeignKey(help_text='Équipement concerné par cette plage de limitation.', on_delete=django.db.models.deletion.CASCADE, related_name='plages_limite', to='equipment.equipement')),
            ],
            options={
                'verbose_name': 'Plage limitée',
                'verbose_name_plural': 'Plages limitées',
                'ordering': ['equipement', 'jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine concerné (0 = Lundi, 6 = Dimanche).')),
                ('heure_debut', models.TimeField(help_text='Heure de début du créneau (ex: 08:00).')),
                ('heure_fin', models.TimeField(help_text='Heure de fin du créneau (ex: 12:00).')),
                ('equipement', models.ForeignKey(help_text='Équipement concerné par ce créneau.', on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='equipment.equipement')),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'ordering': ['equipement', 'jour', 'heure_debut'],
            },
        ),
        migrations.AddConstraint(
            model_name='tarifformation',
            constraint=models.UniqueConstraint(fields=('equipement', 'affiliation'), name='unique_tarif_formation'),
        ),
        migrations.AddConstraint(
            model_name='tarif',
            constraint=models.UniqueConstraint(fields=('equipement', 'affiliation'), name='unique_tarif'),
        ),
    ]
