# Generated by Django 4.2.25 on 2026-05-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['equipment', 'day_of_week', 'start_time'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.AlterModelOptions(
            name='usagequota',
            options={'ordering': ['equipment', 'day_of_week', 'start_time'], 'verbose_name': 'Usage Quota', 'verbose_name_plural': 'Usage Quotas'},
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0 = Monday, 6 = Sunday).'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(help_text='Slot end time (e.g. 12:00).'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='equipment',
            field=models.ForeignKey(help_text='Equipment this time slot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(help_text='Slot start time (e.g. 08:00).'),
        ),
        migrations.AlterField(
            model_name='usagequota',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0 = Monday, etc.).'),
        ),
        migrations.AlterField(
            model_name='usagequota',
            name='end_time',
            field=models.TimeField(help_text='End of the controlled time window.'),
        ),
        migrations.AlterField(
            model_name='usagequota',
            name='equipment',
            field=models.ForeignKey(help_text='Equipment this usage quota applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='usage_quotas', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='usagequota',
            name='max_duration_minutes',
            field=models.PositiveIntegerField(help_text='Maximum cumulative duration allowed per user within this window (in minutes).'),
        ),
        migrations.AlterField(
            model_name='usagequota',
            name='start_time',
            field=models.TimeField(help_text='Start of the controlled time window.'),
        ),
    ]
