# Generated by Django 5.2.1 on 2025-05-31 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'affiliation (ex : YourUniversity, McGill)", max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du laboratoire', max_length=150)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratoires', to='usager.affiliation')),
            ],
            options={
                'unique_together': {('nom', 'affiliation')},
            },
        ),
        migrations.CreateModel(
            name='Usager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(help_text="Prénom de l'usager", max_length=30)),
                ('nom', models.CharField(help_text="Nom de famille de l'usager", max_length=30)),
                ('courriel', models.EmailField(help_text="Adresse courriel de l'usager (unique)", max_length=254, unique=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Compte actif ou désactivé')),
                ('est_admin', models.BooleanField(default=False, help_text="L'usager a les droits administratifs")),
                ('affiliation', models.ForeignKey(blank=True, help_text="Affiliation de l'usager", null=True, on_delete=django.db.models.deletion.SET_NULL, to='usager.affiliation')),
                ('compte_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_usager', to=settings.AUTH_USER_MODEL)),
                ('equipements_accessibles', models.ManyToManyField(blank=True, to='equipements.equipement')),
                ('equipements_autorises', models.ManyToManyField(blank=True, related_name='usagers_autorises', to='equipements.equipement')),
                ('fonction', models.ForeignKey(blank=True, help_text="Fonction de l'usager", null=True, on_delete=django.db.models.deletion.SET_NULL, to='usager.fonction')),
                ('laboratoire', models.ForeignKey(blank=True, help_text="Laboratoire de l'usager", null=True, on_delete=django.db.models.deletion.SET_NULL, to='usager.laboratoire')),
            ],
            options={
                'verbose_name': 'Usager',
                'verbose_name_plural': 'Usagers',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
