# Generated by Django 5.2.2 on 2025-06-05 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usager',
            name='compte_utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usager', to=settings.AUTH_USER_MODEL),
        ),
    ]
