# Generated by Django 5.2.2 on 2025-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0002_alter_usager_compte_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usager',
            name='est_actif',
            field=models.BooleanField(default=False, help_text='Compte actif ou désactivé'),
        ),
    ]
