# Generated by Django 5.2.2 on 2025-06-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0003_alter_usager_est_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usager',
            name='equipements_accessibles',
        ),
    ]
