# Generated by Django 5.2.2 on 2025-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0004_remove_usager_equipements_accessibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='tarif_assistance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Taux horaire (en CAD) pour l'assistance technique", max_digits=6),
        ),
    ]
