# Generated by Django 5.2.2 on 2025-06-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0006_equipement_formation_theorique'),
        ('usager', '0005_affiliation_tarif_assistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courriel', models.EmailField(max_length=254)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('equipements', models.ManyToManyField(to='equipements.equipement')),
            ],
        ),
    ]
