# Generated by Django 4.2.24 on 2025-09-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0008_remove_tarif_tarif_assistance_and_more'),
        ('reserv', '0003_reservation_duree_assistance_minutes'),
        ('usager', '0006_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'accès à l'équipement a été validé", null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Réservation de formation liée à cette invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserv.reservation'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='equipements',
            field=models.ManyToManyField(blank=True, to='equipements.equipement'),
        ),
    ]
