# Generated by Django 4.2.24 on 2025-10-14 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0007_invitation_date_validation_invitation_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
