# Generated by Django 4.2.24 on 2025-10-14 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0008_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_publication'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='usager',
            name='date_activation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usager',
            name='date_derniere_reverification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
