# Generated by Django 4.2.24 on 2025-10-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0009_alter_news_options_usager_date_activation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usager',
            name='date_acceptation_reglement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
