# Generated by Django 4.2.24 on 2025-10-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0010_usager_date_acceptation_reglement'),
    ]

    operations = [
        migrations.AddField(
            model_name='usager',
            name='reglement_accepte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usager',
            name='reglement_accepte_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
