# Generated by Django 5.2.8 on 2026-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0011_usager_reglement_accepte_usager_reglement_accepte_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationFormation',
            fields=[
            ],
            options={
                'verbose_name': 'Validation des formations',
                'verbose_name_plural': 'Validation des formations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usager.invitation',),
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_publication'], 'verbose_name': 'Actualité', 'verbose_name_plural': 'Actualités'},
        ),
        migrations.AddField(
            model_name='news',
            name='categorie',
            field=models.CharField(choices=[('equipement', 'Équipement'), ('evenement', 'Événement'), ('formation', 'Formation')], default='equipement', help_text="Catégorie de l'actualité", max_length=20),
        ),
    ]
