# Generated by Django 4.2.25 on 2026-04-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usager', '0012_invitationformation_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usager',
            name='acknowledgment_inscription',
            field=models.BooleanField(default=False, help_text="L'usager s'est engagé à mentionner la plateforme dans ses publications"),
        ),
        migrations.AlterField(
            model_name='news',
            name='categorie',
            field=models.CharField(choices=[('equipement', 'Équipement'), ('evenement', 'Événement'), ('formation', 'Formation'), ('emploi', "Offre d'emploi")], default='equipement', help_text="Catégorie de l'actualité", max_length=20),
        ),
    ]
