# Generated by Django 4.2.25 on 2026-05-20 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'affiliation (ex : YourUniversity, McGill)", max_length=100, unique=True)),
                ('tarif_assistance', models.DecimalField(decimal_places=2, default=0, help_text="Taux horaire (en CAD) pour l'assistance technique", max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courriel', models.EmailField(max_length=254)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, help_text="Date à laquelle l'accès à l'équipement a été validé", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du laboratoire', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(choices=[('equipement', 'Équipement'), ('evenement', 'Événement'), ('formation', 'Formation'), ('emploi', "Offre d'emploi")], default='equipement', help_text="Catégorie de l'actualité", max_length=20)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Usager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(help_text="Prénom de l'usager", max_length=30)),
                ('nom', models.CharField(help_text="Nom de famille de l'usager", max_length=30)),
                ('courriel', models.EmailField(help_text="Adresse courriel de l'usager (unique)", max_length=254, unique=True)),
                ('reglement_accepte', models.BooleanField(default=False)),
                ('reglement_accepte_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_inscription', models.BooleanField(default=False, help_text="L'usager s'est engagé à mentionner la plateforme dans ses publications")),
                ('est_actif', models.BooleanField(default=False, help_text='Compte actif ou désactivé')),
                ('est_admin', models.BooleanField(default=False, help_text="L'usager a les droits administratifs")),
                ('date_activation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_derniere_reverification', models.DateTimeField(blank=True, null=True)),
                ('date_acceptation_reglement', models.DateTimeField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(blank=True, help_text="Affiliation de l'usager", null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.affiliation')),
                ('compte_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usager',
                'verbose_name_plural': 'Usagers',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
