# Generated by Django 4.2.25 on 2026-05-20 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'affiliation (ex : YourUniversity, McGill)", max_length=100, unique=True)),
                ('assistance_rate', models.DecimalField(decimal_places=2, default=0, help_text="Taux horaire (en CAD) pour l'assistance technique", max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, help_text="Date à laquelle l'accès à l'équipement a été validé", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du laboratory', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('event', 'Event'), ('training', 'Training'), ('job', 'Job offer')], default='equipment', help_text="Catégorie de l'actualité", max_length=20)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Prénom de l'user_profile", max_length=30)),
                ('name', models.CharField(help_text="Nom de famille de l'user_profile", max_length=30)),
                ('email', models.EmailField(help_text="Adresse email de l'user_profile (unique)", max_length=254, unique=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('registration_acknowledged', models.BooleanField(default=False, help_text="L'user_profile s'est engagé à mentionner la plateforme dans ses publications")),
                ('is_active', models.BooleanField(default=False, help_text='Compte is_active ou désactivé')),
                ('is_platform_admin', models.BooleanField(default=False, help_text="L'user_profile a les droits administratifs")),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reverification_date', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(blank=True, help_text="Affiliation de l'user_profile", null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.affiliation')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
                'ordering': ['name', 'first_name'],
            },
        ),
    ]
