# Generated by Django 4.2.25 on 2026-05-20 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('equipment', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authorized_equipment',
            field=models.ManyToManyField(blank=True, related_name='authorized_user_profiles', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='laboratory',
            field=models.ForeignKey(blank=True, help_text="Laboratory de l'user_profile", null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.laboratory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text="Role de l'user_profile", null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='accounts.affiliation'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='equipment_set',
            field=models.ManyToManyField(blank=True, to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Réservation de formation liée à cette invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.reservation'),
        ),
        migrations.CreateModel(
            name='TrainingInvitation',
            fields=[
            ],
            options={
                'verbose_name': 'Validation des formations',
                'verbose_name_plural': 'Validation des formations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.invitation',),
        ),
        migrations.AlterUniqueTogether(
            name='laboratory',
            unique_together={('name', 'affiliation')},
        ),
    ]
