# Generated by Django 4.2.25 on 2026-05-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usager',
            name='equipements_autorises',
            field=models.ManyToManyField(blank=True, related_name='usagers_autorises', to='equipment.equipement'),
        ),
        migrations.AddField(
            model_name='usager',
            name='fonction',
            field=models.ForeignKey(blank=True, help_text="Fonction de l'usager", null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fonction'),
        ),
        migrations.AddField(
            model_name='usager',
            name='laboratoire',
            field=models.ForeignKey(blank=True, help_text="Laboratoire de l'usager", null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.laboratoire'),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratoires', to='accounts.affiliation'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='equipements',
            field=models.ManyToManyField(blank=True, to='equipment.equipement'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Réservation de formation liée à cette invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.reservation'),
        ),
        migrations.CreateModel(
            name='InvitationFormation',
            fields=[
            ],
            options={
                'verbose_name': 'Validation des formations',
                'verbose_name_plural': 'Validation des formations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.invitation',),
        ),
        migrations.AlterUniqueTogether(
            name='laboratoire',
            unique_together={('nom', 'affiliation')},
        ),
    ]
