# Generated by Django 4.2.25 on 2026-05-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('assistance', models.BooleanField(default=False)),
                ('assistance_duration_minutes', models.PositiveIntegerField(blank=True, help_text="Durée de l'assistance technique en minutes (rempli par un admin)", null=True)),
                ('is_training', models.BooleanField(default=False)),
                ('trained_emails', models.TextField(blank=True, help_text='Uniquement pour les réservations de type formation. Séparer les emails par des virgules.')),
                ('exception_request', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True)),
                ('is_maintenance', models.BooleanField(default=False, help_text="Réservation pour maintenance/hors service (bloque l'équipement)")),
                ('is_teaching', models.BooleanField(default=False, help_text='Réservation pour enseignement (cours de labo)')),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('past', 'Passée'), ('cancelled', 'Annulée'), ('pending', 'En attente (exception)')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-start_date', 'start_time'],
            },
        ),
    ]
