# Generated by Django 4.2.25 on 2026-05-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('heure_fin', models.TimeField()),
                ('heure_debut', models.TimeField()),
                ('date_fin', models.DateField()),
                ('assistance', models.BooleanField(default=False)),
                ('duree_assistance_minutes', models.PositiveIntegerField(blank=True, help_text="Durée de l'assistance technique en minutes (rempli par un admin)", null=True)),
                ('est_formation', models.BooleanField(default=False)),
                ('courriels_formes', models.TextField(blank=True, help_text='Uniquement pour les réservations de type formation. Séparer les courriels par des virgules.')),
                ('demande_exception', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True)),
                ('est_maintenance', models.BooleanField(default=False, help_text="Réservation pour maintenance/hors service (bloque l'équipement)")),
                ('est_enseignement', models.BooleanField(default=False, help_text='Réservation pour enseignement (cours de labo)')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('passee', 'Passée'), ('annulee', 'Annulée'), ('en_attente', 'En attente (exception)')], default='a_venir', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipement')),
                ('usager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usager')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_debut', 'heure_debut'],
            },
        ),
    ]
